# Generated by Django 3.1.4 on 2021-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='Departman')),
                ('pbi_id', models.CharField(max_length=100, verbose_name='PBI Id')),
                ('workorder_class', models.CharField(max_length=100, verbose_name='Workorder Class')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('pbi', models.CharField(max_length=100, verbose_name='PBI')),
                ('classficition', models.CharField(max_length=100, verbose_name='Classification')),
                ('workorder_date', models.DateTimeField(verbose_name='Workorder Date')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('finish_date', models.DateTimeField(verbose_name='Finish Date')),
                ('actual_date', models.DateTimeField(verbose_name='Actual Date')),
            ],
        ),
    ]
