# Generated by Django 3.1.4 on 2021-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210110_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='department_name',
            field=models.CharField(default=19, max_length=100, verbose_name='Departmant'),
            preserve_default=False,
        ),
    ]
