# Generated by Django 3.1.4 on 2021-01-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210117_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='department_adress',
        ),
    ]
