# Generated by Django 3.1.4 on 2021-01-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210117_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='home.departments', verbose_name='Departman'),
        ),
    ]
