# Generated by Django 3.1.4 on 2021-01-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210119_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbi',
            old_name='type',
            new_name='pbi_type',
        ),
    ]
