# Generated by Django 3.1.4 on 2021-01-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210120_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbi',
            name='workorder_class',
        ),
    ]
