# Generated by Django 3.1.4 on 2021-01-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_pbi_workorder_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbi',
            old_name='pbi_id',
            new_name='sprint',
        ),
    ]
