# Generated by Django 3.1.4 on 2021-01-23 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210122_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='end_day_index',
            field=models.CharField(default=datetime.datetime(2021, 1, 23, 9, 48, 39, 997234, tzinfo=utc), max_length=100, verbose_name='İş Günü Sayısı'),
            preserve_default=False,
        ),
    ]
