# Generated by Django 3.1.4 on 2021-01-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_pbi_end_day_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Date'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='home.departments', verbose_name='Departman'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finish Date'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='sprint',
            field=models.CharField(default='1/2021', max_length=100, verbose_name='Sprint'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='workorder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Workorder Date'),
        ),
    ]
