# Generated by Django 3.1.4 on 2021-01-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210126_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='classficition',
            field=models.CharField(max_length=100, verbose_name='Sınıflandırma'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitirilmesi Gereken Tarih'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='pbi_type',
            field=models.CharField(max_length=100, verbose_name='PBI Tipi'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='workorder_date',
            field=models.DateField(blank=True, null=True, verbose_name='İş Emri Tarihi'),
        ),
    ]
