# Generated by Django 3.1.4 on 2021-02-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210126_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Date'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='classficition',
            field=models.CharField(max_length=100, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='home.departments', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finish Date'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='pbi',
            field=models.CharField(max_length=200, verbose_name='PBI'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='pbi_type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='sprint',
            field=models.CharField(default='2/2021', max_length=100, verbose_name='Sprint'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='workorder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Workorder Date'),
        ),
    ]
